manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: esyo-net
      url-base: https://github.com/esyo-net
  projects:
    - name: zmk
      remote: esyo-net
      revision: main
      import: app/west.yml
  self:
    path: config
